//
//  SignInPresenter.swift
//  diaswift-example
//
//  Created by John Patrick Teruel on 3/30/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInPresentationLogic
{
  func presentSomething(response: SignIn.Something.Response)
}

class SignInPresenter: SignInPresentationLogic
{
  weak var viewController: SignInDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SignIn.Something.Response)
  {
    let viewModel = SignIn.Something.ViewModel(error: response.error)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
