//
//  SignInViewController.swift
//  diaswift-example
//
//  Created by John Patrick Teruel on 3/30/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInDisplayLogic: class
{
  func displaySomething(viewModel: SignIn.Something.ViewModel)
}

class SignInViewController: UIViewController, SignInDisplayLogic
{
  var interactor: SignInBusinessLogic?
  var router: (NSObjectProtocol & SignInRoutingLogic & SignInDataPassing)?
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SignInInteractor()
    let presenter = SignInPresenter()
    let router = SignInRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    
  }
  
  // MARK: Do something
    
  // MARK: IBOutlets
  @IBOutlet weak var usernameField: UITextField!
  @IBOutlet weak var passwordField: UILabel!
    
    @IBAction func didTapLogin(_ sender: Any) {
        doSomething()
    }
  
  func doSomething()
  {
    guard let username = usernameField.text?.nullableTrimmed,
          let password = passwordField.text?.nullableTrimmed else{
        self.showInvalidInputMessageAlert(message: "Username or Password is not valid.")
        return
    }
    
    let request = SignIn.Something.Request(username: username, password: password)
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: SignIn.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
    if let error = viewModel.error{
        self.showErrorMessageAlert(error: error)
    }else{
        self.showMessageAlert(title: "Success", message: "Successfully logged in.")
    }
  }
    
}
